services:
  - type: web
    name: punto-de-venta
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn proyecto.proyecto.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: proyecto.proyecto.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
    plan: free
