services:
  - type: web
    name: punto-de-venta
    env: python
    buildCommand: 
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn proyecto.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: proyecto.settings
      - key: SECRET_KEY
        value: tu-clave-super-secreta
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        value: tiendacorozo@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: wkti yeec iumn xuxh
    plan: free
