# Generated by Django 5.2 on 2025-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_subtotal_detalleventa_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(default='efectivo', max_length=20),
        ),
    ]
