# Generated by Django 5.2 on 2025-04-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_venta_folio_venta_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id',
        ),
        migrations.AlterField(
            model_name='venta',
            name='folio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(max_length=20),
        ),
    ]
