# Generated by Django 5.2 on 2025-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_cortecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
