# Generated by Django 4.2.6 on 2025-05-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_producto_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='qr_code',
        ),
    ]
