# Generated by Django 4.2.6 on 2025-05-04 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_remove_producto_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El código de barras debe contener solo números y tener entre 8 y 13 dígitos.', regex='^\\d{8,13}$')]),
        ),
    ]
