# Generated by Django 4.2.6 on 2025-05-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_producto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='alerta_stock_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
