# Generated by Django 4.2.6 on 2025-05-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_venta_autorizado_por_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_autorizacion',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
